theme: jekyll-theme-minimal
title: Nuffin is nothing
description: Bookmark this to keep an eye on my project updates!
# them: jekyll-theme-architect
them: jekyll-theme-hacker
# them: jekyll-theme-cayman
# them: jekyll-theme-midnight
